# Generated by Django 2.0.6 on 2018-06-08 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likerecord',
            old_name='user',
            new_name='liked_user',
        ),
    ]
