# Generated by Django 2.0.6 on 2018-06-08 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_auto_20180608_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likerecord',
            old_name='liked_user',
            new_name='user',
        ),
    ]
